<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>


    <parent>
        <groupId>fr.enedis.donnees</groupId>
        <artifactId>bdc-pom-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <groupId>com.mycompany.invoise</groupId>
    <artifactId>core</artifactId>
    <version>1.0-SNAPSHOT</version>

    <name>core</name>
    <!-- FIXME change it to the project's website -->
    <url>http://www.example.com</url>

    <scm>
        <connection>scm:git@gitlab.adaje.oi.enedis.fr:ti-stm/microservices/bdc/bdm-msr-ccmm/index-msr-ccmm-bem-acquisition.git</connection>
        <developerConnection>scm:git:ssh://git@gitlab.adaje.oi.enedis.fr:ti-stm/microservices/bdc/bdm-msr-ccmm/index-msr-ccmm-bem-acquisition.git</developerConnection>
        <url>https://gitlab.adaje.oi.enedis.fr/ti-stm/microservices/bdc/bdm-msr-ccmm/index-msr-ccmm-bem-acquisition.git</url>
        <tag>HEAD</tag>
    </scm>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.8.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement> <!-- https://youtrack.jetbrains.com/issue/IDEA-265664/maven-spring-boot-maven-plugin-is-highlighted-in-red-if-version-is-specified-in-paren-pom -->
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>